- name: This play will demonstrate use of list variable and its loop navigation
  hosts: all
  vars_files:
    - software_tools.yml
  tasks:
    - name: Install software utilities in Ubuntu
      when: ansible_distribution  == "Ubuntu"
      apt: name="{{item}}" state=latest update_cache=yes
      with_list: "{{software_utils}}"

    - name: Install Extra Packages for Enterprise Linux (epel) in CentOS 
      when: ansible_distribution  == "CentOS"
      yum: name=epel-release state=latest 

    - name: Install software utilities in CentOS 
      when: ansible_distribution  == "CentOS"
      yum: name="{{item}}" state=latest 
      with_list: "{{software_utils}}"
